      *> C:\dsg\greed\base.cls
      $SET ALIGN(8)
       78 maxnumberbytes               value h"0FFFFFFF".
      *>>---------------------------------------------------------------
      *>> The size of an object reference
      *>>---------------------------------------------------------------
       78 objectReferenceSize          value length of self.
      *>----------------------------------------------------------------
      *> Return false this is not a metaclass.
      *>----------------------------------------------------------------
